name:                ldgv
version:             0.0.1
github:              "proglang/ldgv"
synopsis:            Frontend, interpreter and C backend for LDGV/LDST
license:             BSD3
license-file:        LICENSE
author:
- "Leon Läufer (LDGVNW implementation)"
- "Thomas Leyh (CCLDLC implementation)"
- "Nils Hagner (web frontend, interpreter)"
- "Janek Spaderna (command line fronted, C backend)"
- "Peter Thiemann (parser, typechecker)"
maintainer:          "thiemann@informatik.uni-freiburg.de"
copyright:           "2019-2023 Chair of Programming Languages, Uni Freiburg"

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-unused-do-bind
- -Wno-unused-matches

extra-doc-files:
- examples/*.ldgv
- examples/*.ccldgv
- examples/*.gldgv
- examples/*.txt
- examples/*.out

data-files:
- c-support/runtime/*.h
- c-support/runtime/*.c

dependencies:
- base >=4.12 && <5
- bytestring
- filepath
- mtl
- text

library:
  source-dirs: src
  other-modules:
  - PrettySyntax
  - TCSubtyping
  - TCTyping
  - TCXMonad
  - C.CPS
  - C.MonadStack
  - Paths_ldgv
  build-tools:
  - alex
  - happy
  dependencies:
  - array
  - containers
  - file-embed
  - lens
  - prettyprinter
  - transformers
  - typed-process
  - validation-selective
  - network
  - network-run
  - random
  - SafeSemaphore >=0.10.1
  - directory

tests:
  ldgv-test:
    main: Spec.hs
    source-dirs: test
    other-modules:
    - ArithmeticSpec
    - CcldlcSpec
    - CSpec
    - FunctionApplicationSpec
    - FunctionSignaturesSpec
    - InterpreterSpec
    - LdlcSpec
    - TypecheckerSpec
    - Utils
    - UtilsFuncCcldlc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools: hspec-discover
    dependencies:
    - ldgv
    - QuickCheck
    - array
    - containers
    - hspec
    - typed-process
    - unliftio

executables:
  ldgv:
    main: Main.hs
    other-modules: Output
    source-dirs: exe
    dependencies:
    - ldgv
    - optparse-applicative
    - prettyprinter
    - prettyprinter-ansi-terminal
    - terminal-size
    - unliftio
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
